### ISSUE TITLE
 ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0

### ISSUE THREAD

**Issue by kermarrecg** [stefanfluck/palmpy#78]
Dear team,
I am trying to make palmpy work for the tutorial case but I get the following error which I am not able to fix:
(base) kermarrec@kornog:~/tmp/anaconda3/lib/python3.10/palmpy/palmpy-main/static generator$ python make_static.py tutorialcase.ini

INFO: Imported the tutorial mapdict.
Could not creat the output path as given in the namelist (e.g. exists already).

domain_0

SUCCESS: Chosen parameters and resulting nx, ny and nz match

Finalizing Checks:

Cell count test: nx, ny and nz are all integers. Test PASSED.
Traceback (most recent call last):
  File "/home/kermarrec/tmp/anaconda3/lib/python3.10/palmpy/palmpy-main/static generator/make_static.py", line 307, in <module>
    gdt.cutortho(ortho, subdir_rasteredshp+filenames+'_baseortho.tif', 
  File "/home/kermarrec/tmp/anaconda3/lib/python3.10/palmpy/staticcreation/geodatatools.py", line 224, in cutortho
    from osgeo import gdal
  File "/home/kermarrec/.local/lib/python3.10/site-packages/osgeo/__init__.py", line 41, in <module>
    _gdal = swig_import_helper()
  File "/home/kermarrec/.local/lib/python3.10/site-packages/osgeo/__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/kermarrec/tmp/anaconda3/lib/python3.10/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/kermarrec/tmp/anaconda3/lib/python3.10/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0

I would really appreciate your support here. Many thanks in advance,
gael.

**Comment by stefanfluck** [comment]
Hi gael
sorry for the very late reply! To me that looks like it could be an issue with the gdal installation on your end. See also my reply to the email you sent me. 
I think I should provide a docker image for a running environment to prevent any such issues in the future.
